language: scala
jdk:
- oraclejdk8
before_install:
- git fetch --tags
- ./setup-coursier.sh
- export PATH="$PATH:$(pwd)/coursier/modules/cli/target/pack/bin"
script: sbt test:compile
cache:
  directories:
  - $HOME/.cache
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - scala: 2.12.7
  - stage: release
    script: coursier publish
